spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/menupilot}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false

server:
  port: 8080

stripe:
  secret: ${STRIPE_SECRET:}
  webhookSecret: ${STRIPE_WEBHOOK_SECRET:}
  priceId: ${STRIPE_PRICE_ID:}

app:
  baseUrl: ${APP_BASE_URL:http://localhost:8080}

logging:
  level:
    org.hibernate.SQL: warn

upload:
  dir: ${UPLOAD_DIR:/tmp/menupilot-uploads}

# SMTP (optional). If set, emails will send; otherwise HTML renders to console.
spring:
  mail:
    host: ${SMTP_HOST:}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USER:}
    password: ${SMTP_PASS:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mail:
  from: ${MAIL_FROM:noreply@menupilot.local}

# HTTPS / proxy support
server:
  forward-headers-strategy: native
  ssl:
    enabled: ${SERVER_SSL_ENABLED:false}
    key-store: ${SERVER_SSL_KEY_STORE:}
    key-store-password: ${SERVER_SSL_KEY_STORE_PASSWORD:}
    key-store-type: ${SERVER_SSL_KEY_STORE_TYPE:PKCS12}
    key-alias: ${SERVER_SSL_KEY_ALIAS:}

app:
  forceHttps: ${APP_FORCE_HTTPS:false}
